load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.2"
RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

# This creates another external workspace named @maven. 
# So if we would need a different version of the same artifact (same groupId, and same artifactId), 
# we would just create another target maven_install(name="maven1", ..) 
# and refer to the artifact in the different version: @maven1//...
maven_install(
    artifacts = [
      "org.apache.commons:commons-compress:1.20",
      "commons-io:commons-io:2.7",
      "org.tukaani:xz:1.8",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

load("//:bazel/download_url.bzl", "download_url")
download_url(
  name="index-germanium",
  url="http://germaniumhq.com/",
)
download_url(
  name="index-google",
  url="https://google.com/",
)