# tag::all[]
# tag::targets[]
# Page - 32
genrule(
  name="documentation",
  srcs=[
    "src/README.md",
  ],
  outs=[
      "documentation.zip",
  ],
  cmd="zip $(OUTS) $(SRCS)"
)
# end::targets[]
# end::all[]

